apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    description: This is cluster ip svc for mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
