apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask.fullname" . }}
  labels:
    app: {{ include "flask.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask.fullname" . }}
    spec:
      containers:
        - name: flaskapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: MYSQL_HOST
              value: "{{ .Values.mysql.host }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_DB
              value: "{{ .Values.mysql.database }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          imagePullPolicy: Always
