apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask.fullname" . }}-mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}  # Encoding the password in base64
