apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}-service
spec:
  selector:
    app: {{ include "flask.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
