apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.initDBConfigMap }}  # ConfigMap name, sourced from values.yaml
data:
  init.sql: |
    -- Create the database if it doesn't exist
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};

    -- Switch to the created database
    USE {{ .Values.mysql.database }};

    -- Create the messages table
    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,   -- Unique ID for each message
        fullname VARCHAR(255) NOT NULL,      -- Full name of the user
        emailaddress VARCHAR(255) NOT NULL,  -- Email address
        phonenumber VARCHAR(15) NOT NULL,    -- Phone number
        message TEXT NOT NULL,               -- The message content
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Timestamp of creation
    );
