apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}  # Encoding root password in base64
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}  # Encoding MySQL user in base64
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}  # Encoding user password in base64
