apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  selector:
    app: {{ include "mysql.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  type: {{ .Values.service.type }}
