apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}  # Reference to the Secret name from values.yaml
data:
  secret-key-1: {{ .Values.secretValues.My_Sql_Password | b64enc | quote }}
