apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "two-tier-app.name" . }}-flask
  labels:
    app: {{ include "two-tier-app.name" . }}-flask
spec:
  replicas: {{ .Values.replicaCountFlask }}
  selector:
    matchLabels:
      app: {{ include "two-tier-app.name" . }}-flask
  template:
    metadata:
      labels:
        app: {{ include "two-tier-app.name" . }}-flask
    spec:
      containers:
        - name: two-tier-app
          image: "{{ .Values.imageFlask.repository }}:{{ .Values.imageFlask.tag }}"
          env:
            - name: MYSQL_HOST
              value: {{ include "two-tier-app.name" . }}-mysql
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_DB
              value: {{ .Values.mysql.database }}
          ports:
            - containerPort: {{ .Values.serviceFlask.targetPort }}
          imagePullPolicy: Always
