apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "two-tier-app.name" . }}-mysql
  labels:
    app: {{ include "two-tier-app.name" . }}-mysql
spec:
  replicas: {{ .Values.replicaCountMysql }}
  selector:
    matchLabels:
      app: {{ include "two-tier-app.name" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "two-tier-app.name" . }}-mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.imageMysql.repository }}:{{ .Values.imageMysql.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "two-tier-app.name" . }}-mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          ports:
            - containerPort: {{ .Values.serviceMysql.port }}
          volumeMounts:
            - name: mysql-initdb
              mountPath: docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: {{ include "two-tier-app.name" . }}-mysql-initdb-config
