apiVersion: v1
kind: Service
metadata:
  name: {{ include "two-tier-app.name" . }}-mysql
spec:
  selector:
    app: {{ include "two-tier-app.name" . }}-mysql
  ports:
    - port: {{ .Values.serviceMysql.port }}
      targetPort: {{ .Values.serviceMysql.port }}
  type: {{ .Values.serviceMysql.type }}
