apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
data:
  secret-key-1: {{ .Values.secretValues.My_Sql_Password | b64enc | quote }}
  secret-key-2: {{ .Values.secretValues.My_Sql_Database | b64enc | quote }}
  secret-key-3: {{ .Values.secretValues.My_Sql_User | b64enc | quote }}

