service:
  type: LoadBalancer  
  port: 80
  targetPort: 5000

labels:
  traffic: active # It will be changed dynamically at the time of deployment
  app: blue  # It will be changed dynamically at the time of deployment

ingress:
  enabled: true
  className: "nginx" # Specify the Ingress class
  hosts:
    prod: "prod-flaskapp.us.to"
    qaPreprod: "qapreprod-flaskapp.us.to"
  services:
    prod:
      name: "service-flaskapp-prod"
      port: 80
    qaPreprod:
      name: "service-flaskapp-preprod"
      port: 80
