apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE messages (fullname VARCHAR(255), emailaddress VARCHAR(255), phonenumber VARCHAR(20), message TEXT );
