replicaCount: 2

image:
  repository: preranamauryaa/portfolioflaskapp
  tag: latest

service:
  type: LoadBalancer  
  port: 80
  targetPort: 5000

mysql:
  host: mysql  #change it with the cluster ip of mysql
  user: Prerana
  password: Newuser@#12345
  database: contact
