replicaCountMysql: 1
replicaCountFlask: 2

imageMysql:
  repository: mysql
  tag: "latest"

imageFlask:
  repository: preranamauryaa/portfolioflaskapp
  tag: "latest"

mysql:
  rootPassword: "admin"
  user: "admin"
  password: "admin"
  database: "mydb"

serviceMysql:
  type: ClusterIP
  port: 3306

serviceFlask:
  type: LoadBalancer
  port: 80
  targetPort: 5000

configMapMysql:
  initSql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE messages (fullname VARCHAR(255), emailaddress VARCHAR(255), phonenumber VARCHAR(20), message TEXT );
