apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-prod
spec:
  selector:
    traffic: blue-traffic
  type: {{ .Values.service.type }}  
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
